import { delay, randomError } from "../utils";
import { mockEvents } from "../data/events";
import { mockAttendance } from "../data/attendance";
import { mockPhotos } from "../data/photos";
import { mockUsers } from "../data/users";
import { mockMemberDetails } from "../data/memberships";
import { CreateEventDto, EventPhoto, UploadResponse, SendInvitationsResponse, EventInvitation, EventInvitationStatus, AttendanceAnalytics, AttendanceTrends } from "@/lib/types";

let events = [...mockEvents];
let attendance = [...mockAttendance];
let photos = [...mockPhotos];

export const eventMock = {
  getEvents: async (mahberId: string, page = 1, limit = 20) => {
    await delay(600);
    const filteredEvents = events.filter((e) => e.mahber_id === mahberId);
    const sorted = filteredEvents.sort(
      (a, b) =>
        new Date(b.start_time).getTime() - new Date(a.start_time).getTime(),
    );
    const total = sorted.length;
    const totalPages = Math.ceil(total / limit) || 1;
    const startIndex = (page - 1) * limit;
    const endIndex = startIndex + limit;
    const data = sorted.slice(startIndex, endIndex);
    return {
      data,
      meta: { total, page, limit, totalPages },
    };
  },

  getEventById: async (mahberId: string, eventId: string) => {
    await delay(400);
    const event = events.find(
      (e) => e.mahber_id === mahberId && e.id === eventId,
    );
    if (!event) throw new Error("Event not found");
    return event;
  },

  createEvent: async (mahberId: string, data: CreateEventDto) => {
    await delay(800);
    randomError(0.05);
    const newEvent = {
      id: `evt_${Date.now()}`,
      mahber_id: mahberId,
      title: data.title,
      description: data.description,
      event_type: data.event_type,
      start_time: data.start_time,
      end_time: data.end_time,
      location: data.location,
      is_mandatory: data.is_mandatory || false,
      is_cancelled: false,
      created_at: new Date().toISOString(),
    };
    events = [newEvent, ...events];
    return newEvent;
  },

  updateEvent: async (
    mahberId: string,
    eventId: string,
    data: Partial<CreateEventDto>,
  ) => {
    await delay(600);
    const index = events.findIndex(
      (e) => e.mahber_id === mahberId && e.id === eventId,
    );
    if (index === -1) throw new Error("Event not found");
    events[index] = { ...events[index], ...data };
    return events[index];
  },

  cancelEvent: async (mahberId: string, eventId: string) => {
    await delay(700);
    const index = events.findIndex(
      (e) => e.mahber_id === mahberId && e.id === eventId,
    );
    if (index === -1) throw new Error("Event not found");
    events[index].is_cancelled = true;
    return events[index];
  },

  getQRCode: async (mahberId: string, eventId: string) => {
    await delay(500);
    // Return a dummy data URI representing a mock QR code image.
    // In a real app, this would be a real base64 image generated by the backend.
    return {
      qr_code:
        "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxNTAiIGhlaWdodD0iMTUwIiB2aWV3Qm94PSIwIDAgMTUwIDE1MCI+PHJlY3Qgd2lkdGg9IjE1MCIgaGVpZ2h0PSIxNTAiIGZpbGw9IiNmZmYiLz48cmVjdCB4PSIyMCIgeT0iMjAiIHdpZHRoPSIxMTAiIGhlaWdodD0iMTEwIiBmaWxsPSIjMDAwIi8+PHJlY3QgeD0iMzAiIHk9IjMwIiB3aWR0aD0iOTAiIGhlaWdodD0iOTAiIGZpbGw9IiNmZmYiLz48cmVjdCB4PSI0MCIgeT0iNDAiIHdpZHRoPSI3MCIgaGVpZ2h0PSI3MCIgZmlsbD0iIzAwMCIvPjwvc3ZnPg==",
    };
  },

  getUserQRCode: async (mahberId: string, eventId: string) => {
    await delay(500);
    // Return a mock user-specific QR code (different from event QR)
    // In a real app, this would generate a unique token per user
    return {
      qr_code:
        "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxNTAiIGhlaWdodD0iMTUwIiB2aWV3Qm94PSIwIDAgMTUwIDE1MCI+PHJlY3Qgd2lkdGg9IjE1MCIgaGVpZ2h0PSIxNTAiIGZpbGw9IiNmZmYiLz48cmVjdCB4PSIxNSIgeT0iMTUiIHdpZHRoPSIxMjAiIGhlaWdodD0iMTIwIiBmaWxsPSIjMDAwIi8+PHJlY3QgeD0iMjUiIHk9IjI1IiB3aWR0aD0iMTAwIiBoZWlnaHQ9IjEwMCIgZmlsbD0iI2ZmZiIvPjxyZWN0IHg9IjM1IiB5PSIzNSIgd2lkdGg9IjgwIiBoZWlnaHQ9IjgwIiBmaWxsPSIjMDAwIi8+PC9zdmc+",
    };
  },

  checkIn: async (mahberId: string, eventId: string, qrToken: string) => {
    await delay(1000);
    randomError(0.1);
    const newAttendance = {
      id: `att_${Date.now()}`,
      event_id: eventId,
      member_id: mockUsers[2].id, // Simulating a check-in from a specific user
      mahber_id: mahberId,
      checked_in_at: new Date().toISOString(),
      user: mockUsers[2],
    };
    attendance = [newAttendance, ...attendance];
    return newAttendance;
  },

  getPhotos: async (
    mahberId: string,
    eventId: string,
    page = 1,
    limit = 20,
  ) => {
    await delay(600);
    const filteredPhotos = photos.filter((p) => p.event_id === eventId);
    const total = filteredPhotos.length;
    const totalPages = Math.ceil(total / limit);
    const startIndex = (page - 1) * limit;
    const endIndex = startIndex + limit;
    const data = filteredPhotos.slice(startIndex, endIndex);
    return {
      data,
      meta: { total, page, limit, totalPages },
    };
  },

  uploadPhoto: async (
    mahberId: string,
    eventId: string,
    formData: FormData,
  ) => {
    await delay(1200);
    // Handle multiple file uploads if provided under 'files' or 'file'
    const files =
      (formData.getAll("files") as File[]) ||
      (formData.getAll("file") as File[]) ||
      [];

    const caption = (formData.get("caption") as string) || undefined;

    // If multiple files provided, create a photo record for each
    if (files && files.length > 0) {
      const newPhotos = files.map((f, i) => {
        const p: EventPhoto = {
          id: `pht_${Date.now()}_${i}`,
          event_id: eventId,
          mahber_id: mahberId,
          uploader_id: mockUsers[2].id,
          // Use a unique Unsplash image URL as a mock for each file
          file_path: `https://images.unsplash.com/photo-1491438590914-bc09fcaaf77a?q=80&w=80${Math.floor(
            Math.random() * 900,
          )}&auto=format&fit=crop`,
          caption: caption || f.name || "New photo upload",
          created_at: new Date().toISOString(),
          user: mockUsers[2],
        };
        return p;
      });
      photos = [...newPhotos, ...photos];
      return { data: newPhotos, meta: { uploaded: newPhotos.length } };
    }

    // No files provided - fall back to generating a single mock photo
    const newPhoto: EventPhoto = {
      id: `pht_${Date.now()}`,
      event_id: eventId,
      mahber_id: mahberId,
      uploader_id: mockUsers[2].id,
      file_path:
        "https://images.unsplash.com/photo-1491438590914-bc09fcaaf77a?q=80&w=800&auto=format&fit=crop",
      caption: caption || "New photo upload",
      created_at: new Date().toISOString(),
      user: mockUsers[2],
    };
    photos = [newPhoto, ...photos];
    return { data: [newPhoto], meta: { uploaded: 1 } };
  },

  deletePhoto: async (mahberId: string, eventId: string, photoId: string) => {
    await delay(600);
    const index = photos.findIndex(
      (p) => p.id === photoId && p.event_id === eventId,
    );
    if (index === -1) throw new Error("Photo not found");
    photos.splice(index, 1);
  },

  // ── Invitations ─────────────────────────────────────────────────────────
  mockInvitations: [] as EventInvitation[],

  sendInvitations: async (
    mahberId: string,
    eventId: string,
    memberIds: string[],
  ): Promise<SendInvitationsResponse> => {
    await delay(800);
    randomError(0.05);

    const existing = eventMock.mockInvitations.filter(
      (inv) => inv.event_id === eventId,
    );
    const alreadyInvitedIds = new Set(existing.map((inv) => inv.member_id));
    const newMemberIds = memberIds.filter((id) => !alreadyInvitedIds.has(id));

    const newInvitations: EventInvitation[] = newMemberIds.map((memberId) => {
      const member = mockMemberDetails.find((m) => m.member_id === memberId);
      return {
        id: `inv_${Date.now()}_${memberId}`,
        event_id: eventId,
        mahber_id: mahberId,
        member_id: memberId,
        status: "Pending" as EventInvitationStatus,
        sent_at: new Date().toISOString(),
        channels_used: ["in_app", "fcm", "email", "sms"],
        member: member?.user,
      };
    });

    eventMock.mockInvitations = [
      ...eventMock.mockInvitations,
      ...newInvitations,
    ];

    return {
      invited: newInvitations.length,
      already_invited: memberIds.length - newInvitations.length,
      invalid_members: 0,
      invitations: newInvitations,
    };
  },

  getInvitations: async (mahberId: string, eventId: string) => {
    await delay(500);
    return eventMock.mockInvitations.filter((inv) => inv.event_id === eventId);
  },

  respondToInvitation: async (
    mahberId: string,
    eventId: string,
    invitationId: string,
    action: "accept" | "decline",
  ) => {
    await delay(600);
    const idx = eventMock.mockInvitations.findIndex(
      (inv) => inv.id === invitationId,
    );
    if (idx === -1) throw new Error("Invitation not found");
    eventMock.mockInvitations[idx].status =
      action === "accept" ? ("Accepted" as EventInvitationStatus) : ("Declined" as EventInvitationStatus);
    eventMock.mockInvitations[idx].responded_at = new Date().toISOString();
    return eventMock.mockInvitations[idx];
  },

  getMyInvitations: async (mahberId: string) => {
    await delay(500);
    return eventMock.mockInvitations.filter(
      (inv) =>
        inv.mahber_id === mahberId &&
        inv.member_id === mockUsers[2].id &&
        inv.status === "Pending",
    );
  },

  // ── Registration / RSVP ──────────────────────────────────────────────────
  registerForEvent: async (mahberId: string, eventId: string) => {
    await delay(600);
    randomError(0.05);

    const existing = eventMock.mockInvitations.find(
      (inv) => inv.event_id === eventId && inv.member_id === mockUsers[2].id,
    );
    if (existing?.status === "Accepted") {
      throw new Error("Already registered");
    }

    const newReg: EventInvitation = {
      id: `reg_${Date.now()}`,
      event_id: eventId,
      mahber_id: mahberId,
      member_id: mockUsers[2].id,
      status: "Accepted",
      sent_at: new Date().toISOString(),
      responded_at: new Date().toISOString(),
      source: "self_register",
      channels_used: ["in_app"],
      member: mockUsers[2],
    };

    if (existing) {
      const idx = eventMock.mockInvitations.findIndex(
        (inv) => inv.id === existing.id,
      );
      eventMock.mockInvitations[idx] = newReg;
    } else {
      eventMock.mockInvitations = [...eventMock.mockInvitations, newReg];
    }

    return newReg;
  },

  cancelRegistration: async (mahberId: string, eventId: string) => {
    await delay(500);
    const idx = eventMock.mockInvitations.findIndex(
      (inv) =>
        inv.event_id === eventId &&
        inv.member_id === mockUsers[2].id &&
        inv.status === "Accepted",
    );
    if (idx === -1) throw new Error("No active registration found");
    eventMock.mockInvitations.splice(idx, 1);
    return { message: "Registration cancelled successfully" };
  },

  getRegistrations: async (mahberId: string, eventId: string) => {
    await delay(500);
    const all = eventMock.mockInvitations.filter(
      (inv) => inv.event_id === eventId && inv.mahber_id === mahberId,
    );
    const accepted = all.filter((inv) => inv.status === "Accepted");
    const declined = all.filter((inv) => inv.status === "Declined");
    const pending = all.filter((inv) => inv.status === "Pending");
    return {
      total_active_members: mockMemberDetails.filter(
        (m) => m.mahber_id === mahberId && m.status === "Active",
      ).length,
      summary: {
        registered: accepted.length,
        declined: declined.length,
        pending: pending.length,
        no_response: 0,
      },
      registrations: accepted,
      invitations: { declined, pending },
    };
  },

  processAttendance: async (mahberId: string, eventId: string) => {
    await delay(1000);
    randomError(0.05);
    return { message: "Attendance processing job queued" };
  },

  getAttendance: async (mahberId: string, eventId: string) => {
    await delay(600);
    const data = attendance.filter((a) => a.event_id === eventId);
    return {
      data,
      meta: { total: data.length, page: 1, limit: 20, totalPages: 1 },
    };
  },

  // ── Analytics (Mock) ───────────────────────────────────────────────────────
  getAttendanceAnalytics: async (_mahberId: string, _eventId: string) => {
    await delay(400);
    const total_members = 12;
    const attended = 9;
    return {
      event_id: _eventId,
      total_members,
      attended,
      absent: total_members - attended,
      attendance_percentage: Math.round((attended / total_members) * 100),
      is_mandatory: true,
      is_cancelled: false,
    } satisfies AttendanceAnalytics;
  },

  getAttendanceTrends: async (_mahberId: string, _eventId: string, months = 6) => {
    await delay(500);
    const trends = [];
    const now = new Date();
    for (let i = months - 1; i >= 0; i--) {
      const d = new Date(now.getFullYear(), now.getMonth() - i, 1);
      const month = d.toISOString().slice(0, 7);
      trends.push({
        month,
        event_count: 2 + Math.floor(Math.random() * 4),
        total_members: 12,
        total_attended: 7 + Math.floor(Math.random() * 4),
        average_attendance_rate: 60 + Math.floor(Math.random() * 30),
      });
    }
    return { trends, total_active_members: 12 } satisfies AttendanceTrends;
  },

  exportAttendanceReport: async (_mahberId: string, _eventId: string, _params?: any) => {
    await delay(800);
    const dummyPdf = new Uint8Array(100);
    return new Blob([dummyPdf], { type: 'application/pdf' });
  },
};
